apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "testkube-samples.componentName" (dict "root" . "component" "api") }}
  labels:
    {{- include "testkube-samples.labels" (dict "root" . "component" "api") | nindent 4 }}
  {{- with .Values.api.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
